### PR TITLE
Primal dual

### PR DESCRIPTION
**Pull request by rodrigo-pena**
Implemented two primal-dual algorithms from [Komodakis and Pesquet, 2015]. For that, I created a class primal_dual() that inherits from solver(). The idea is that all primal-dual algorithms inherit from this parent class primal_dual(), because eu need to set the transformation from primal to dual space, as well as keep track of the dual solutions.

I added documentation and simple tests in the manner as the ones for the other solver modules.

### CODE REVIEW

**Comment by mdeff** [comment]
Thanks for the pull request ! :-) Agreed with the general design (discussed beforehand).

**Comment by mdeff** [comment]
The commits 95ac573 and 25e43ac change images (doc/tutorials/*.{pdf,png}). These were not actually changed, but were regenerated during testing, and thus appeared changed to git. Can you remove them from your commits ?

**Comment by rodrigo-pena** [comment]
How do i remove files from a previous commit?

Rodrigo Pena

Ecole Polytechnique Fédérale de Lausanne
Signal Processing Laboratory 2 (LTS2)
1015 Lausanne - Switzerland
E-mail: rodrigo.pena@epfl.ch<mailto:rodrigo.pena@epfl.ch>
Phone: +41 21 69 37894


On 28 Jul 2016, at 15:14, Michaël Defferrard <notifications@github.com<mailto:notifications@github.com>> wrote:


The commits 95ac573<https://github.com/epfl-lts2/pyunlocbox/commit/95ac573c13e63f5d178a9d420d67c6c0d4f70a96> and 25e43ac<https://github.com/epfl-lts2/pyunlocbox/commit/25e43ac3b76fa9a1aa1b44795b1bff696fadac7c> change images (doc/tutorials/*.{pdf,png}). These were not actually changed, but were regenerated during testing, and thus appeared changed to git. Can you remove them from your commits ?

**Comment by mdeff** [comment]
We have to rewrite history, i.e. git rebase. I've done it. You don't have any further change to base on this branch right ?

**Comment by mdeff** [comment]
I added the dependency on scipy.

**Comment by rodrigo-pena** [comment]
No, I don’t have any further changes

Rodrigo Pena

Ecole Polytechnique Fédérale de Lausanne
Signal Processing Laboratory 2 (LTS2)
1015 Lausanne - Switzerland
E-mail: rodrigo.pena@epfl.ch<mailto:rodrigo.pena@epfl.ch>
Phone: +41 21 69 37894


On 28 Jul 2016, at 17:08, Michaël Defferrard <notifications@github.com<mailto:notifications@github.com>> wrote:


We have to rewrite history, i.e. git rebase. I've done it. You don't have any further change to base on this branch right ?

**Pull request merged**
