### PR TITLE
fixed verbosity for generalized forward backward

### PR DESCRIPTION
**Pull request by ersisimou**

### CODE REVIEW

**Comment by rodrigo-pena** [comment]
Thanks for the fix, Ersi.

**Comment by mdeff** [comment]
Thanks @ersisimou! And welcome to the club of contributors. ;)

**Comment by rodrigo-pena** [comment]
Oh, I completely ignored those. I thought there was no issue in merging because those errors were not raised by @ersisimou ’s file changes. I’ll pay more attention to that in the future.

**Comment by mdeff** [comment]
No problem. ;) Two were due to @ersisimou's changes (the "line too long"). The others were indeed unrelated. I guess they appeared due to an update of the checking tool...

**Pull request merged**
