### PR TITLE
Test tight

### PR DESCRIPTION
**Pull request by nperraud**
Raise an error if a user define a weighed tight L2 norm function

### CODE REVIEW

**Comment by nperraud** [comment]
closes: #19

**Comment by mdeff** [comment]
Thanks! Is that applicable to other functions than the l2 norm?

**Comment by nperraud** [comment]
I thought for the l1 norm as well... But eventually I think not. I am not entirely sure. It would take me quite a lot of math and testing to be sure. So I suggest to stop here.

**Comment by mdeff** [comment]
Sure. I'm not even convinced we should try to catch user errors. After all this library is made for users that want control. It is not a black-box optimization tool.

**Pull request merged**
